# Generated by Django 5.2.8 on 2025-12-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_usuario_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, default='usuario/default.png', null=True, upload_to='usuario/'),
        ),
    ]
