# Generated by Django 5.2.8 on 2025-12-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogos', '0002_jogo_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='imagem',
            field=models.ImageField(upload_to='jogos/'),
        ),
    ]
