# Generated by Django 5.2.8 on 2025-12-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='generos/'),
        ),
    ]
